# Generated by Django 4.2.4 on 2023-08-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('nomor', models.CharField(max_length=15)),
                ('kartu', models.CharField(max_length=12)),
                ('nomorWa', models.CharField(max_length=15)),
                ('pulsa', models.CharField(max_length=20)),
                ('harga', models.CharField(max_length=20)),
                ('jam', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
