# Generated by Django 4.2.4 on 2023-08-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='employee',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='react',
            name='department',
        ),
        migrations.AddField(
            model_name='react',
            name='harga',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='nomorHp',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='pembayaran',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='pulsa',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
