# Generated by Django 4.2.4 on 2023-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_employee_react_nama_remove_react_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='nomorHp',
            new_name='nomor',
        ),
        migrations.RemoveField(
            model_name='react',
            name='pembayaran',
        ),
        migrations.AddField(
            model_name='react',
            name='jam',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='kartu',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='nomorWa',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
