###
GET http://127.0.0.1:8000/


###
POST http://127.0.0.1:8000/send-otp/
content-type: application/json

{
    "nomorWa":"6285212454896"
}

###
POST http://127.0.0.1:8000/verify-otp/
content-type: application/json

{
    "otp":"8888",
    "pulsa":"Rp.10000",    
    "kartu":"Tellkomsel",    
    "nama":"hallo",    
    "nomor":"6285212454896",    
    "harga":"Rp.12.0000",    
    "nomorWa":"085212454896",    
    "status":"belum bayar",    
    "jam":"23"

}


###
POST http://127.0.0.1:8000/checkout/bipulsa85212345566
content-type: application/json

{
    "token":"6285212454896"
}